package com.yozzibeens.rivostaxi.modelo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yozzibeens.rivostaxi.modelo.Client;
import com.yozzibeens.rivostaxi.modelo.Historial;
import com.yozzibeens.rivostaxi.modelo.Favorite_Place;
import com.yozzibeens.rivostaxi.modelo.Favorite_Cabbie;

import com.yozzibeens.rivostaxi.modelo.ClientDao;
import com.yozzibeens.rivostaxi.modelo.HistorialDao;
import com.yozzibeens.rivostaxi.modelo.Favorite_PlaceDao;
import com.yozzibeens.rivostaxi.modelo.Favorite_CabbieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clientDaoConfig;
    private final DaoConfig historialDaoConfig;
    private final DaoConfig favorite_PlaceDaoConfig;
    private final DaoConfig favorite_CabbieDaoConfig;

    private final ClientDao clientDao;
    private final HistorialDao historialDao;
    private final Favorite_PlaceDao favorite_PlaceDao;
    private final Favorite_CabbieDao favorite_CabbieDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clientDaoConfig = daoConfigMap.get(ClientDao.class).clone();
        clientDaoConfig.initIdentityScope(type);

        historialDaoConfig = daoConfigMap.get(HistorialDao.class).clone();
        historialDaoConfig.initIdentityScope(type);

        favorite_PlaceDaoConfig = daoConfigMap.get(Favorite_PlaceDao.class).clone();
        favorite_PlaceDaoConfig.initIdentityScope(type);

        favorite_CabbieDaoConfig = daoConfigMap.get(Favorite_CabbieDao.class).clone();
        favorite_CabbieDaoConfig.initIdentityScope(type);

        clientDao = new ClientDao(clientDaoConfig, this);
        historialDao = new HistorialDao(historialDaoConfig, this);
        favorite_PlaceDao = new Favorite_PlaceDao(favorite_PlaceDaoConfig, this);
        favorite_CabbieDao = new Favorite_CabbieDao(favorite_CabbieDaoConfig, this);

        registerDao(Client.class, clientDao);
        registerDao(Historial.class, historialDao);
        registerDao(Favorite_Place.class, favorite_PlaceDao);
        registerDao(Favorite_Cabbie.class, favorite_CabbieDao);
    }
    
    public void clear() {
        clientDaoConfig.getIdentityScope().clear();
        historialDaoConfig.getIdentityScope().clear();
        favorite_PlaceDaoConfig.getIdentityScope().clear();
        favorite_CabbieDaoConfig.getIdentityScope().clear();
    }

    public ClientDao getClientDao() {
        return clientDao;
    }

    public HistorialDao getHistorialDao() {
        return historialDao;
    }

    public Favorite_PlaceDao getFavorite_PlaceDao() {
        return favorite_PlaceDao;
    }

    public Favorite_CabbieDao getFavorite_CabbieDao() {
        return favorite_CabbieDao;
    }

}
