package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITE__PLACE.
 */
public class Favorite_Place {

    private Long id;
    private String Place_Favorite_Id;
    private String Name;
    private String Description;
    private String Latitude;
    private String Longitude;

    public Favorite_Place() {
    }

    public Favorite_Place(Long id) {
        this.id = id;
    }

    public Favorite_Place(Long id, String Place_Favorite_Id, String Name, String Description, String Latitude, String Longitude) {
        this.id = id;
        this.Place_Favorite_Id = Place_Favorite_Id;
        this.Name = Name;
        this.Description = Description;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlace_Favorite_Id() {
        return Place_Favorite_Id;
    }

    public void setPlace_Favorite_Id(String Place_Favorite_Id) {
        this.Place_Favorite_Id = Place_Favorite_Id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

}
