package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HISTORIAL.
 */
public class Historial {

    private Long id;
    private String Request_Id;
    private String Inicio;
    private String Destino;
    private String Date;
    private String Cabbie;

    public Historial() {
    }

    public Historial(Long id) {
        this.id = id;
    }

    public Historial(Long id, String Request_Id, String Inicio, String Destino, String Date, String Cabbie) {
        this.id = id;
        this.Request_Id = Request_Id;
        this.Inicio = Inicio;
        this.Destino = Destino;
        this.Date = Date;
        this.Cabbie = Cabbie;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRequest_Id() {
        return Request_Id;
    }

    public void setRequest_Id(String Request_Id) {
        this.Request_Id = Request_Id;
    }

    public String getInicio() {
        return Inicio;
    }

    public void setInicio(String Inicio) {
        this.Inicio = Inicio;
    }

    public String getDestino() {
        return Destino;
    }

    public void setDestino(String Destino) {
        this.Destino = Destino;
    }

    public String getDate() {
        return Date;
    }

    public void setDate(String Date) {
        this.Date = Date;
    }

    public String getCabbie() {
        return Cabbie;
    }

    public void setCabbie(String Cabbie) {
        this.Cabbie = Cabbie;
    }

}
