package com.YozziBeens.rivostaxi.modelo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TARJETA.
 */
public class Tarjeta {

    private Long id;
    private String Card_Id;
    private String Name;
    private String Last4;
    private String Exp_Month;
    private String Exp_Year;
    private String Brand;

    public Tarjeta() {
    }

    public Tarjeta(Long id) {
        this.id = id;
    }

    public Tarjeta(Long id, String Card_Id, String Name, String Last4, String Exp_Month, String Exp_Year, String Brand) {
        this.id = id;
        this.Card_Id = Card_Id;
        this.Name = Name;
        this.Last4 = Last4;
        this.Exp_Month = Exp_Month;
        this.Exp_Year = Exp_Year;
        this.Brand = Brand;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCard_Id() {
        return Card_Id;
    }

    public void setCard_Id(String Card_Id) {
        this.Card_Id = Card_Id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getLast4() {
        return Last4;
    }

    public void setLast4(String Last4) {
        this.Last4 = Last4;
    }

    public String getExp_Month() {
        return Exp_Month;
    }

    public void setExp_Month(String Exp_Month) {
        this.Exp_Month = Exp_Month;
    }

    public String getExp_Year() {
        return Exp_Year;
    }

    public void setExp_Year(String Exp_Year) {
        this.Exp_Year = Exp_Year;
    }

    public String getBrand() {
        return Brand;
    }

    public void setBrand(String Brand) {
        this.Brand = Brand;
    }

}
