package com.YozziBeens.rivostaxi.modelo;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.YozziBeens.rivostaxi.modelo.Tarjeta;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TARJETA.
*/
public class TarjetaDao extends AbstractDao<Tarjeta, Long> {

    public static final String TABLENAME = "TARJETA";

    /**
     * Properties of entity Tarjeta.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Card_Id = new Property(1, String.class, "Card_Id", false, "CARD__ID");
        public final static Property Name = new Property(2, String.class, "Name", false, "NAME");
        public final static Property Last4 = new Property(3, String.class, "Last4", false, "LAST4");
        public final static Property Exp_Month = new Property(4, String.class, "Exp_Month", false, "EXP__MONTH");
        public final static Property Exp_Year = new Property(5, String.class, "Exp_Year", false, "EXP__YEAR");
        public final static Property Brand = new Property(6, String.class, "Brand", false, "BRAND");
    };


    public TarjetaDao(DaoConfig config) {
        super(config);
    }
    
    public TarjetaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TARJETA' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CARD__ID' TEXT," + // 1: Card_Id
                "'NAME' TEXT," + // 2: Name
                "'LAST4' TEXT," + // 3: Last4
                "'EXP__MONTH' TEXT," + // 4: Exp_Month
                "'EXP__YEAR' TEXT," + // 5: Exp_Year
                "'BRAND' TEXT);"); // 6: Brand
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TARJETA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Tarjeta entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Card_Id = entity.getCard_Id();
        if (Card_Id != null) {
            stmt.bindString(2, Card_Id);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(3, Name);
        }
 
        String Last4 = entity.getLast4();
        if (Last4 != null) {
            stmt.bindString(4, Last4);
        }
 
        String Exp_Month = entity.getExp_Month();
        if (Exp_Month != null) {
            stmt.bindString(5, Exp_Month);
        }
 
        String Exp_Year = entity.getExp_Year();
        if (Exp_Year != null) {
            stmt.bindString(6, Exp_Year);
        }
 
        String Brand = entity.getBrand();
        if (Brand != null) {
            stmt.bindString(7, Brand);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Tarjeta readEntity(Cursor cursor, int offset) {
        Tarjeta entity = new Tarjeta( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Card_Id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Last4
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Exp_Month
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Exp_Year
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // Brand
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Tarjeta entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCard_Id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLast4(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setExp_Month(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setExp_Year(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBrand(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Tarjeta entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Tarjeta entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
